"""add ondelete cascade

Revision ID: 33826f475fe2
Revises: 49c30065db7b
Create Date: 2022-09-01 21:17:11.975423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33826f475fe2'
down_revision = '49c30065db7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_persons_student_id_fkey', 'contact_persons', type_='foreignkey')
    op.create_foreign_key(None, 'contact_persons', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teachers_to_students_teacher_id_fkey', 'teachers_to_students', type_='foreignkey')
    op.drop_constraint('teachers_to_students_student_id_fkey', 'teachers_to_students', type_='foreignkey')
    op.create_foreign_key(None, 'teachers_to_students', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teachers_to_students', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers_to_students', type_='foreignkey')
    op.drop_constraint(None, 'teachers_to_students', type_='foreignkey')
    op.create_foreign_key('teachers_to_students_student_id_fkey', 'teachers_to_students', 'students', ['student_id'], ['id'])
    op.create_foreign_key('teachers_to_students_teacher_id_fkey', 'teachers_to_students', 'teachers', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'contact_persons', type_='foreignkey')
    op.create_foreign_key('contact_persons_student_id_fkey', 'contact_persons', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
