version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-ice
    restart: unless-stopped
    ports:
      - "80:5000"
    networks:
      - app-networks
  db:
    image: "mongo:latest"
    container_name: db
    restart: unless-stopped
    volumes:
      - /e/datadb:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge